### ISSUE TITLE
Support transaction simulation

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#728] opened 2022-11-13 12:46 UTC
Create `pathfinder_simulateTransaction` as an RPC counter-part to the gateway's [simulate transaction](https://cairo-lang.org/docs/hello_starknet/cli.html#simulate-transaction) interface.

It is essentially a copy of `starknet_estimateFee` but additionally also returns the execution trace.

The plan is to add it formally as part of `v0.3` of the RPC specification, but that is still a while off. In the meantime we can help the ecosystem by supporting it as a pathfinder specific extension.

**Comment by CHr15F0x** [comment] 2023-04-14 05:18
Duplicate of #887

**Closed by CHr15F0x** 2023-04-14 05:18 UTC
