### ISSUE TITLE
Include receipt commitment in the block header

### ISSUE THREAD

**Issue by CHr15F0x** [eqlabs/pathfinder#2108] opened 2024-07-04 11:21 UTC
And:
- add a migration that recomputes the commitment for existing blocks

**Comment by kkovaacs** [comment] 2024-07-15 12:46
Isn't this a duplicate of #2078?

**Comment by kkovaacs** [comment] 2024-07-16 07:38
Also: is the receipt commitment for old blocks actually used anywhere else than P2P? If no, then I'd say we should just skip the migration and only populate receipt commitment for newly synced blocks.

**Comment by CHr15F0x** [comment] 2024-07-16 09:02
> Isn't this a duplicate of #2078?
Not really imo, that one is only about computation.

**Comment by CHr15F0x** [comment] 2024-07-16 09:02
> Isn't this a duplicate of #2078?
Not really imo, that one is only about computation.

**Comment by CHr15F0x** [comment] 2024-07-16 09:02
> Also: is the receipt commitment for old blocks actually used anywhere else than P2P? If no, then I'd say we should just skip the migration and only populate receipt commitment for newly synced blocks.

Nope, no migration needed then.

**Comment by CHr15F0x** [comment] 2024-07-16 09:04
Duplicate of #2078

**Closed** 2024-07-16 12:16 UTC
